POST http://localhost:3003/api/blogs/67753a3112da6c6b43513a10/comments
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdW5vbWF0byIsImlkIjoiNjc3ZWI0NjU2Y2I0MmM4NDI2ODQ1N2M5IiwiaWF0IjoxNzM2MzYxMDk5fQ.KVOtZoHB02TJfJbXo2Ikzg5M3nhdAzoiV8Vv4PCVIZ4

{
    "comment": "awesome blog"
}